repos:
  - repo: local
    hooks:
      - id: uv-format
        name: Format code
        entry: python scripts/format.py
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: uv-lint
        name: Lint code
        entry: python scripts/lint.py
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: uv-test
        name: Unit tests
        entry: python scripts/test.py
        language: system
        pass_filenames: false
        types: [python]
        stages: [pre-commit]
      - id: commitizen-check
        name: Check commit message
        entry: cz check --commit-msg-file
        language: system
        stages: [commit-msg]
